version: '2'

services:
  app:
    restart: always
    logging:
      options:
        max-size: 25k
    networks:
#      - docker_default
      - redis_default
    image: ethercalc:alpine
    build: .
    external_links:
      - redis_db_1
    environment:
      VIRTUAL_HOST: calc.noflag.org.uk
      VIRTUAL_PORT: 8000
    hostname: calc.noflag.org.uk

networks:
  default:
    external:
      name: docker_default