version: '2'

services:
  app:
    restart: always
    logging:
      options:
        max-size: 25k
    networks:
      - redis
    external_links:
      - redis:redis
    image: ethercalc:alpine
    build: .
    external_links:
      - redis_db_1
    environment:
      VIRTUAL_HOST: ethercalc
      VIRTUAL_PORT: 8000

networks:
  default:
    external:
      name: docker_default
  redis:
    external:
      name: redis_default

